session = "session.toml"

[terminal]
# pane_id = 0
# session_name = "main"
command_timeout = 10

[provider]
url = "https://api.deepseek.com"
# or use env OPENAI_API_KEY
key = ""
model = "deepseek-v4-pro"
context_limit = 1000000
