[project]
name = "information-evolution"
version = "0.1.0"
description = ""
requires-python = ">=3.12"
dependencies = [
    "openai>=2.37.0",
    "python-dotenv>=1.0.0",
    "rtoml>=0.13.0",
    "toml>=0.10.2",
]

[dependency-groups]
dev = [
    "pyright[nodejs]>=1.1.409",
    "ruff",
]

[tool.ruff]
line-length = 100

[tool.pyright]
venvPath = "."
venv = ".venv"
